output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks.cluster_security_group_id
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks.kubeconfig
}

output "config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = module.eks.config_map_aws_auth
}

output "region" {
  description = "AWS region"
  value       = var.region
}

output "cluster_name" {
  description = "Kubernetes Cluster Name"
  value       = local.cluster_name
}

output "private_key" {
  value     = tls_private_key.this.private_key_pem
  sensitive = true
}

output "nlb_hostname" {
  value = data.kubernetes_service.traefik.load_balancer_ingress.0.hostname
}

output "elb_hostname" {
  value = data.kubernetes_service.traefik-elb.load_balancer_ingress.0.hostname
}
